### ISSUE TITLE
Properties not working

### ISSUE THREAD

**Issue by jantunes91** [xtianus79/multiple-date-picker-a2#1]
Hi,
I just stumbled upon your angular 2 version of multiple date picker. I'm trying to use it as described in the original docs, but I'm having some issues.
Specifically, If I do something like
`<multiple-date-picker #datePicker [(ngModel)]="dateArray" week-days-off="[0, 3]" disable-navigation="true"></multiple-date-picker>`
the week-days-off and disable-navigation are not propagated onto the view. Is there something different in this version or am I doing something wrong?
thanks in advance!

**Comment by xtianus79** [comment]
Hi @jantunes91 i really need to push my updates and update the docs.  I will do so today... if I can't robustly update the docs I will post a working example here in this thread

**Comment by gangfang** [comment]
@xtianus79 could you please update the docs? 

That will be much appreciated thanks!

**Comment by gangfang** [comment]
Hello @xtianus79 ?

**Comment by xtianus79** [comment]
Yes, I am really sorry... I will try to get something up there today.  It here is a sample config to get your started. 


@gangfang 

<multiple-date-picker
                [showDaysOfSurroundingMonths]="false"
                [disallowBackPastMonths]="true"
                [sundayFirstDay]="true"
                [matIcons]="true"
                disableDaysBefore="true"
                [(ngModel)]="selectedDays"
            >
            </multiple-date-picker>

**Comment by AishwaryT** [comment]
@xtianus79  "week-days-off" and other properties still not working, if you can suggest what i can do to make it work, that would be great.
Thanks

**Comment by xtianus79** [comment]
Do you know all the properties that aren't working... I am going to update this today.... I will configure week-days-off and the other ones you mention.

**Comment by xtianus79** [comment]
@AishwaryT I have fixed your issue... I have a new build coming today... with code clean up, bug fixes and new functionality!!!

**Comment by AishwaryT** [comment]
@xtianus79 , Thanks a lot, its working now.
