### ISSUE TITLE
Get selectedDays

### ISSUE THREAD

**Issue by Robstaer** [xtianus79/multiple-date-picker-a2#2]
Hello and thanks for your wonderful work!

I'm struggeling with an issue i'm not able to resolve for a few days now, that's why i'm asking here directly:

How can i access {{pickedDays}} directly and asign a variable in jquery to it?

http://stackoverflow.com/questions/43897324/multiple-date-picker-to-jquery-variable

Here i asked on stackoverflow, without a solution...

Something like:

var arrayDates = []; 
arrayDates = {{pickedDays}};

Do you have any ideas?

Thanks in advance!

**Comment by xtianus79** [comment]
@Robstaer are you using this for Angularjs or Angular

**Comment by xtianus79** [comment]
@Robstaer sorry I don't know what you're referring to exactly but this is for Angular 2+ not jquery.... I am going to close this issue.  please restate your question if you need additional help.
